alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: profile-app
    match:
      path:
        prefix: /
  - component:
      name: profile-app-static
    match:
      path:
        prefix: /static
name: octopus-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: bre-gilliland/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: profile-app
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/03/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: bre-gilliland/PythonWebApps
  name: profile-app-static
  source_dir: Student/03/Superhero/static

